name: Continuous Integration Build

on: [push, pull_request]

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master
          
      - name: Display Codacy API token
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        run: echo "token=$CODACY_API_TOKEN"
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn test
      
      - uses: vebr/jest-lcov-reporter@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./dist/reports/coverage/lcov.info
        
      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: ./dist/reports/coverage/lcov.info
